### ISSUE TITLE
Tauon crashes when unpaused

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/Tauon#1006]
I have a global play/pause shortcut and noticed today several crashes when unpausing the local playing song.
It happens at random time.

```
(tauon.py:3): Gdk-CRITICAL **: 20:31:16.100: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Applying theme: Cucumber Splash
ph: Connected using samplerate 44100hz
tauonmb: ../../src/cairo-surface.c:930: cairo_surface_reference: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed.
/app/bin/com.github.taiko2k.tauonmb.sh: line 14:     3 Aborted                 (core dumped) python3 /app/bin/tauon.py "$@"
```

Tauon v7.6.6 flatpak

**Comment by C0rn3j** [comment]
Can you still reproduce this in current Tauon version?

If so, are you able to reproduce it more reliably?

I might take a stab at it if it's still a problem.

**Comment by Solarunit** [comment]
No, I haven't noticed it lately. I gonna close it for now.
