### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by madprops** [Taiko2k/Tauon#1042]
![tauncpu](https://github.com/Taiko2k/TauonMusicBox/assets/206498/5e6aa171-7207-4479-a4c3-dc3ac8c06433)

Wanted to report that something caused Tauon to use cpu very heavily.

I noticed it when I saw the cpu temperature was pretty high.

It seemed to fluctuate, this was taken a few seconds before:

![tauoncpu](https://github.com/Taiko2k/TauonMusicBox/assets/206498/99420bf5-424c-4f62-a810-3cf5bdbaefb0)

I closed it and restarted it, cpu back to normal.

**Comment by Solarunit** [comment]
What were you playing at that moment, local files, radio?
I had high cpu usage when playing radio for a long time.

(also is that btop on the screenshot?)

**Comment by madprops** [comment]
> What were you playing at that moment, local files, radio? I had high cpu usage when playing radio for a long time.
> 
> (also is that btop on the screenshot?)

I was playing local files, I don't play radio radio on Tauon, I use audacious for that. The only thing weird I guess I did before was try the Lockdown mode for a while, but I doubt it was that. Also the internet here disconnects very often. Yes that's btop on the screenshot.

**Comment by madprops** [comment]
This is happening every time I open Tauon now, right at startup, it goes to around 30% cpu and more when I start playing something.

**Comment by Taiko2k** [comment]
@madprops So to clarify it will stay high after startup even if nothing is playing?

**Comment by madprops** [comment]
Just by opening Tauon it now goes to over 200% cpu, while unstarted/paused. I saw 600% for a second.

**Comment by madprops** [comment]
![tauon234](https://github.com/Taiko2k/TauonMusicBox/assets/206498/25df3a3a-e4c1-4459-aa16-bdf92571fc80)

**Comment by madprops** [comment]
Tried flatpak again today. High cpu process at first launch. I closed it and re-launched it. CPU seemed lower now but at a constant ~9% python process which is still very high.

**Comment by madprops** [comment]
Alright that seems to have altered the cpu consumption. It now idles at 0-2% as you said, and jumps to 4-7% when playing which is ok. I'll close this now, thanks.
