### ISSUE TITLE
covers of tracks from the subsonic server

### ISSUE THREAD

**Issue by pooh2pooh** [Taiko2k/Tauon#1054]
Hi! Thank you, wonderful player! <3

There is a problem with the display of covers, I download the library from the Subsonic server,
there are more covers on the server itself.
There are only two in Tauron.

**Tauon 7.6.7 on Arch Linux**, package from AUR
If you click Re-scan tags from the Meta section, the application ends with a log:
```
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Gallery render error!
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 359, in <module>
    exec(main)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 45568, in <module>
    playlist_render.full_render()
  File "/opt/tauon-music-box/t_modules/t_main.py", line 33868, in full_render
    track_id = track_object.index
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'index'
```

![изображение](https://github.com/Taiko2k/TauonMusicBox/assets/21198356/11c620e5-5bd6-45ef-b3e8-14e7888f6640)
![изображение](https://github.com/Taiko2k/TauonMusicBox/assets/21198356/5cb7f5e6-0e78-4a1b-ae85-39a346c35eb0)

**Comment by C0rn3j** [comment]
Closing as dupe https://github.com/Taiko2k/Tauon/issues/1225 which is newer but more active, if you have some spare time grab `AUR/tauon-music-box-git` and retest there please.
