### ISSUE TITLE
python-tekore error

### ISSUE THREAD

**Issue by ParadoxPacer** [Taiko2k/Tauon#1129]
I got Tauon working on macos, as per [your instructions](https://github.com/Taiko2k/TauonMusicBox/issues/577).

I even got the .app working by using the "pyinstaller mac.spec --clean --noconfirm" command.

![Untitled 2](https://github.com/Taiko2k/TauonMusicBox/assets/149180602/a89c7050-665c-42b0-901b-324883a78472)

However, when logging into spotify, i run into this error:
<img width="675" alt="Screenshot 2024-04-15 at 21 56 52" src="https://github.com/Taiko2k/TauonMusicBox/assets/149180602/ce38d656-0a87-428a-8953-4b717431d4e1">

I already installed tekore
<img width="1166" alt="image" src="https://github.com/Taiko2k/TauonMusicBox/assets/149180602/7dcfc626-bd2e-4bb5-9965-856c89196652">

and after restarting multiple times, im still running into this issue

**Comment by Taiko2k** [comment]
Try run `python3 tauon.py` before the pyinstaller step and try it. If that works then it would be an issue with how the app is being packaged. Don't ask me how to fix it though, I kind of gave up on macOS support due to difficulties with pyinstaller.

**Comment by ParadoxPacer** [comment]
This worked, thank you.

By the way, the way to get build working is by first replacing line 14 (dbus-python) in requirements.txt with dbus-next, since dbus-python is deprecated

Then i ran 'pip3 install -r requirements.txt'

Then i ran "bash compile-phazor.sh"

After that, i ran "python3 tauon.py" in the TauonMusicbox directory

I got the pyinstaller step working by first installing pyinstaller with `pip3 install pyinstaller`

Then i installed ffmpeg@5 with 'brew install ffmpeg@5' since ffmpeg 6 is kinda broken.

Then i changed line 12 of mac.spec from '(prefix + '/bin/ffmpeg', '.'),' to '(prefix + '/Cellar/ffmpeg@5', '.'),'

And then i ran "pyinstaller mac.spec --clean --noconfirm" and that worked fine, i now have the .app file in ~/TauonMusicbox/dist

**Comment by dmt-hub** [comment]
@ParadoxPacer 
Thanks for your tips, i can run tauon on macos via python3 tauon.py, but i can't get the app working, when i start the app it stops before it even opens.

Any ideas how i could solve this?

Thanks in advance.

**Comment by C0rn3j** [comment]
7.9.0 has large changes to the build system which should fix the dependency loading issue.

#1348 automates DMG building

@dmt-hub you need to somehow extract the DMG and the APFS file from within it and launch it like so afterwards

```python
🌱 | [495]  /Applications/TauonMusicBox.app/Contents/MacOS/Tauon\ Music\ Box    [14:45]  

Traceback (most recent call last):
  File "sdl2/dll.py", line 362, in <module>
  File "sdl2/dll.py", line 253, in __init__
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: /usr/local/opt/sdl2_image/lib)
```

Would be nice to get that documented for debugging.

Please test the #1348 DMGs if you have the times, let's get those running peachy so people don't have to build manually.
