### ISSUE TITLE
libappindicator is abandoned

### ISSUE THREAD

**Issue by stkw0** [Taiko2k/Tauon#1133]
Last libappindicator version dates from 2012 (see https://launchpad.net/libappindicator). This can be a problem when installing or packaging tauon at tome point in a near future. Can be a good idea to study alternatives.

**Comment by Taiko2k** [comment]
Good point. OK Ive now committed a change for Tauon to use Ayatana Indicator instead. So from next release the dependency will be libayatana-appindicator instead if libappindicator.
