### ISSUE TITLE
Wrong encoding used with certain .cue file

### ISSUE THREAD

**Issue by soredake** [Taiko2k/Tauon#1139]
![image](https://github.com/Taiko2k/TauonMusicBox/assets/5204968/35aab7b4-58d4-4da4-90ad-5097d6f71724)

Sample:
[ПОСЛЕ ТРЕТЬЕЙ ХОДКИ.zip](https://github.com/Taiko2k/TauonMusicBox/files/15139647/default.zip)

**Comment by Taiko2k** [comment]
This should be fixed now with last release. (v7.8.0)
