### ISSUE TITLE
[Feature request] No titles replayed until all others have been played

### ISSUE THREAD

**Issue by toto789** [Taiko2k/Tauon#1149]
In shuffle mode, no title should be played again until all the others have been played.

**Comment by toto789** [comment]
Doesn't anyone care but me? Isn't that an obvious feature?

**Comment by Taiko2k** [comment]
Tauon already has repeat avoidance, but in response to this issue I tweaked it to fix some edge cases (released in v7.8.0, I just forgot to update this issue). 

Give it a try, import some tracks into a playlist, turn on shuffle mode and press next successively. It should play every track in the playlist once only before any repeat. If not can you tell me the steps to reproduce?

**Comment by toto789** [comment]
Hey !!!!!!!!!!!!!!!! Well done and thank you! One point against Quod Libet! ;-)
