### ISSUE TITLE
[Feature request] Playlist and artist repeat

### ISSUE THREAD

**Issue by Alan1CC** [Taiko2k/Tauon#1167]
I want to start by saying that you did an AMAZING job with this music player. It's fast becoming my main music player on PC. My only gripe with it is that's it's annoying to restart my playlist (which is just a compilation of all of an artist's music) whenever it ends.
I think playlist repeat should've been done before album repeat because once you're able to repeat a playlist, you can put as much or as little music you want. You can put an album or an entire discography in it.
Artist replay is only secondary, I don't think it's that important if you add the playlist repeat.

I wish you all the luck with development. Have a nice day!

**Comment by Taiko2k** [comment]
There is a global setting for playlist repeat in the Settings.

**Comment by Alan1CC** [comment]
I've checked the entirety of the settings thrice before requesting and I did not find it. Could you supply a screenshot?

**Comment by Taiko2k** [comment]
It should be under Settings > Playlist > End of playlist action, there you can set that to repeat playlist.

**Comment by Alan1CC** [comment]
There is no playlist section.
Just to make sure we are on the same page, we are talking about this settings menu?
![image](https://github.com/Taiko2k/Tauon/assets/101445275/505284a4-70e5-426c-9d8e-63b13c5b6729)

**Comment by Taiko2k** [comment]
Sorry try "Tracklist" I mean. If not there try "Function" and check over the numbered tabs at the bottom. I'm not at my computer right now so can't check.

**Comment by Alan1CC** [comment]
Oh! That is what the numbers on the bottom were? I completely looked over those.
Thanks for telling me about this, there is indeed a repeat playlist option on tab 2.
