### ISSUE TITLE
Crashes when streaming with Discord

### ISSUE THREAD

**Issue by Thermo-Dyn** [Taiko2k/Tauon#1175]
Tauon 7.8.0
Windows 11 23H2

Tauon crashes when streaming it to Discord. If it's not playing it won't, but if you interact with the window or the application in any way it will crash. It will immediately crash upon starting the stream if already playing. It appears that this only happens with Discord and not OBS or anything else.

**Comment by C0rn3j** [comment]
If it still happens on 7.8.3, having the crash log with the trace would be nice.

I suppose you may be able to get it if you launch Tauon from Powershell, but unsure.

**Comment by C0rn3j** [comment]
I've tagged this issue as to close when a PR that fixes building on Windows lands, if you can reproduce it even then from master or the future 7.9.0, tag me or open a new issue.
