### ISSUE TITLE
last.fm support no longer functional in v7.8.0 on Windows

### ISSUE THREAD

**Issue by tsukijin** [Taiko2k/Tauon#1188]
i didn't see an issue for this so i'm not sure if its already been kept in mind for the next update or not. 
v7.7.2 still has perfectly working last.fm support, but on v7.8.0 it breaks despite maintaining the account login. specifically, its the "Optional module python-pylast not installed" error.
i've uninstalled and reinstalled both versions and logged in/out multiple times with the same results and no other errors. 
for the record, i'm running Windows 10 Home 22H2 19045.4651

**Comment by tsukijin** [comment]
i decided to try building Tauon myself since the guide is very straightforward. i did manage to complete the build, after a few issues along the way. i want to document what i did in case there's any other windows users who've had the same issue, however i did **not** save any error logs or anything (i almost gave up lol).

in terms of issues with the build instructions:
- step 9: as far as i could find online, there is no `librespot.exe` available to download, at least easily. so copying it from a previous installation is what i did.
- step 10: i received an error every time i ran the `pip install -r extra/win-requirements.txt` command, **until** i removed OpenCC from the list. after the command completed successfully, attempting to `pip install opencc` still returned the same error that my non-programmer brain couldn't unravel.
- to install OpenCC (which i'm not sure is even truly essential?) i opened a normal command prompt and ran `pip install opencc`. afterwards, i copied over both new folders from the Windows site-packages folder (`C:\Python312\Lib\site-packages`, for me) to the MSYS2 site-packages folder. (`C:\msys64\mingw64\lib\python3.11\site-packages`)
- step 11: running `bash compile-phazor.sh` failed instantly with the main error being "_Package libgme was not found in the pkg-config search path._". but i could not figure out how to solve this issue until i found [a link](https://packages.msys2.org/package/mingw-w64-x86_64-libgme) with the command `pacman -S mingw-w64-x86_64-libgme` which instantly fixed the error and led me to successfully finish the build.
- running `python tauon.py` before packaging into an exe showed that last.fm support worked on the newest version when building it manually. however, once i ran `bash win-build.sh` and started up the exe as normal, last.fm support completely broke again. since i am completely out of my depth here, i figured i would just use the old version forever lol.
so, most importantly, while i can't tell you why v7.7.2 last.fm support works out the box and 7.8.x doesn't even after manually building, i _can_ tell you that what *does* fix it is by simply running `pip install pylast` in a normal windows command prompt. and that's it! [:)](https://open.spotify.com/album/0hm7PiBu72tRliLqLfiKy1)

**Comment by C0rn3j** [comment]
Do I get it correctly that your issue was resolved in both the prebuilt version and the manual version by force installing pylast?

OpenCC is an optional library for improving Simplified vs Traditional Chinese searches, from what I understand.

**Comment by Taiko2k** [comment]
Its likely a Pyinstaller issue. `pylast` seems really finicky with it, we even have specific hook files https://github.com/Taiko2k/Tauon/tree/master/extra/pyinstaller-hooks for it but it seems those are no longer sufficient. I haven't looked more deeply into what the error exactly is but it works when running from terminal (not packaged into exe using pyinstaller).

More broadly Ive been having a lot of issues with pyinstaller lately, I'm almost tempted to look at alternatives but I'm not sure what that might be.

**Comment by C0rn3j** [comment]
OpenCC being pulled on Windows is fixed in https://github.com/Taiko2k/Tauon/pull/1352, everything else mentioned should be too.
