### ISSUE TITLE
Middle Click goes through Settings

### ISSUE THREAD

**Issue by madprops** [Taiko2k/Tauon#1196]
Funny thing happens, I guess because it's calculated by coordinates, but if I middle click part of the settings window, it triggers the queue on the album below it, I mean it goes through.

![hover234](https://github.com/user-attachments/assets/3c55a75e-a1c7-4555-9131-876109f36e8f)

Not an issue but maybe it shouldn't do actions like that when a window is open

**Comment by Taiko2k** [comment]
Ok committed a fix for this.

**Comment by madprops** [comment]
Awesome, congrats on 3,500 commits
