### ISSUE TITLE
Glitches when working with the system

### ISSUE THREAD

**Issue by machitgarha** [Taiko2k/Tauon#1211]
First, thanks for developing this, every other player miss a feature or two.

The main problem - and it is a big issue - is when I increase the load of a system a bit, the music that is playing starts glitching. By a bit, I mean really tiny things, like opening a tab in Firefox, or opening a new lightweight application. It's really annoying, and I don't have this problem with one other player I tested, Elisa.

Even stranger, when Tauon is opened and I've played at least one song with it, and I play something else (doesn't matter if it's music or video), the playback also glitches in the case of a tiny workload (tested with a video on VLC and a music on Elisa). When I close Tauon, the glitches are gone.

**Comment by machitgarha** [comment]
My environment is Fedora 40, and I'm using the Flathub version. I'm using Pipewire and Wireplumber, if it helps. Tell me if you need more information.

**Comment by Taiko2k** [comment]
Try go MENU > Setting > Open config file, then increase the value of device-buffer-ms, maybe to about 200. Save, exit and restart Tauon.

**Comment by machitgarha** [comment]
Thanks for the quick reply! The problem is gone!

May I know why this was the case?

**Comment by Taiko2k** [comment]
It may be that the default value is too low, but I'm not sure why some systems exhibit the issue and others don't.

**Comment by machitgarha** [comment]
:thinking: Alright. Thanks again.
