### ISSUE TITLE
[Feature] Log window

### ISSUE THREAD

**Issue by litemotiv** [Taiko2k/Tauon#1214]
It would be nice if Tauon had an optional log window that could be pulled up to see the status of certain background processes such as:

- Library importing / parsing 
- Chromecast connection 
- Bio and lyrics fetching 
- Album art fetching
- Scrobbling

etc.

Tauon is a Swiss army knife with a lot of things happening in the background, which can make it difficult (for end users) to find out what is happening when something doesn't work right away. Easily accessible information about certain processes could help users to gain more insight and to provide better feedback for bug reports. 

A possible inspiration could be the log window in Nicotine+, which can be opened/closed with a 3-dot icon in the lower corner:

![2024-08-21_10-25](https://github.com/user-attachments/assets/64c25981-eabd-4558-8871-009054266759)

**Comment by litemotiv** [comment]
I must have completely missed that, thanks @Solarunit !

I'll just close this ticket then. ;-)

**Comment by Taiko2k** [comment]
While the log window does exist, not all features log to it. If a features needs better feedback then it might be best to open an issue to address how best to improve that on a case by case basis.
