### ISSUE TITLE
Output CUE parsing errors to log window

### ISSUE THREAD

**Issue by litemotiv** [Taiko2k/Tauon#1219]
V7.8.1

When a CUE sheet can't be parsed correctly, it currently fails silently. It would be helpful if parse errors could be logged to the log window, to help debug the cause. 

Below is an example of a CUE that cannot be parsed correctly, resulting in an empty playlist entry. The log window shows no errors:

![2024-08-29_10-37](https://github.com/user-attachments/assets/b8b6f1db-de20-4b7e-b0c1-95c3bac94ae3)

**Comment by Taiko2k** [comment]
OK Ive committed a change for this now

**Comment by C0rn3j** [comment]
I presume this can be closed then, especially with the reworked logging system for 7.9.0.
