### ISSUE TITLE
use left or right on keyboard to fast forward or rewind a song

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/Tauon#1227]
as of now left or right do move the selection of an item (eg a tab) but it would be nice to have those buttons to fast forward o rewind a song :)

**Comment by Taiko2k** [comment]
You can configure this using the `input.txt` file in the user data folder. Look for the keys `cycle-playlist-right` and `seek-forward`.

**Comment by legacychimera247** [comment]
i feel this should be actually exposed into the ui but it was exactly what i was looking for, thank you

should i close this one if you don't intend to put it into the ui?

**Comment by Taiko2k** [comment]
I think its too complicated to add this to the UI.
