### ISSUE TITLE
Could be a good idea to move phazor to a different directory?

### ISSUE THREAD

**Issue by stkw0** [Taiko2k/Tauon#1230]
I was thinking that having phazor in the same repository that Tauon may not be ideal. Seems phazor is more stable (it doesn't change that much) than Tauon. Separating it allows updating Tauon without requiring a rebuild of phazor. This would also make it easier from packagers perspective.

**Comment by Taiko2k** [comment]
Not really, they're heavily connected, it doesn't really make sense to split it.
