### ISSUE TITLE
info on italian translation

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/Tauon#1234]
Hello, when i go in tauon there are some strings that are still unstranslated, but weblate says italian is 100% done, how is this possible?thank you...

**Comment by Taiko2k** [comment]
Not all strings are internally marked for translation. Could you give an example of a non translated string?

**Comment by legacychimera247** [comment]
here are some examples :)

![Schermata del 2024-09-11 12-02-21](https://github.com/user-attachments/assets/3adf6c52-884b-42c6-854c-bab86141d0c7)
![Schermata del 2024-09-11 12-02-34](https://github.com/user-attachments/assets/04951b08-0eb9-4d14-bdff-599db9a5e59f)
![Schermata del 2024-09-11 12-02-38](https://github.com/user-attachments/assets/5757cb7d-8699-47ca-bac3-145c9131db0c)

**Comment by legacychimera247** [comment]
also, donate (for the donate option) and "rescan all folders" in the database menu

those are the ones that right now comes into my mind

**Comment by Taiko2k** [comment]
Oh actually that wasn't the issue, it was my script wasn't working right, Ive fixed it and updated weblate now with the missing strings. There may still be some that just haven't been marked, but we will have to wait for a new release cycle of tauon to find those.

**Comment by legacychimera247** [comment]
ah thank you, will do the new ones then
