### ISSUE TITLE
Tauon breaks under pipewire backend if gst playbin is playing audio while nothing else is

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/Tauon#1245]
* I can 100% repro this with TMB in native pipweire backend (does not happen with Pulse) playing some music, 
* gst playbin playing a sound  
* NOTHING ELSE playing sounds to the point of not appearing in pw-top

`pw-top` then starts throwing massive amount of errors for the TMB process:

![image](https://github.com/user-attachments/assets/8f0d9e70-a488-45e3-95f6-858fb51ddefd)

This causes audio to break intermittently while playbin is playing audio, and has a chance to kill or revive the audio in TMB when it stops.

I initially [reported the bug to PipeWire](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4334) but I am unsure who is at fault here.

Is this a PW issue or a TMB issue?

**Comment by Taiko2k** [comment]
Ive made a minor change as suggested in that therad. @C0rn3j are you familiar with building Tauon from source, could you test latest master and see if there is any change in audio?

**Comment by C0rn3j** [comment]
I've packaged git version of Tauon as [AUR/tauon-music-box-git](https://aur.archlinux.org/packages/tauon-music-box-git) and I am unable to reproduce there.

I am consistently able to reproduce by switching to latest stable.

So I suppose this was on TMB, thanks a lot!
