### ISSUE TITLE
Repeat Track does not work in Tauon 7.8.3 (option does not appear)

### ISSUE THREAD

**Issue by MinuteNewt** [Taiko2k/Tauon#1246]
What the title says. When the Repeat button is clicked, only Repeat Album is enabled. When the repeat button is clicked again, it just turns repeating off. So there is no option to repeat the current track, the option simply doesn't appear. I'm on Linux Mint 22, Cinnamon desktop, version 6.2.9.

**Comment by Solarunit** [comment]
I just tested it, repeat track works for me.

**Comment by Taiko2k** [comment]
You need to right click the button to bring up the menu to switch it back to repeat track

**Comment by MinuteNewt** [comment]
> You need to right click the button to bring up the menu to switch it back to repeat track

Right you are, I forgot. I'm used to cycling through the repeat states by left clicking. I'm closing the issue.
