### ISSUE TITLE
Spotify not working

### ISSUE THREAD

**Issue by DashD87** [Taiko2k/Tauon#1314]
I add spotify playlist to Tauon, but the preparing spotify playback not working.

**Comment by C0rn3j** [comment]
Can you reproduce it on latest git master version?

If so, what's in the log about it?

**Comment by C0rn3j** [comment]
If you can reproduce this on one of the prebuilt images (currently in #1354, click the checkmark on the latest commit and go to the Summary where you can download one), report back with the log from Tauon (tap ` or open it from Misc) along with details about your OS and we'll reopen it.
