### ISSUE TITLE
XSPF export produces incorrectly encoded tags

### ISSUE THREAD

**Issue by iamalexei** [Taiko2k/Tauon#1331]
Commit 0a59adc04af6813d1bae9d737754af8d2ecfd98c fixed the issue https://github.com/Taiko2k/Tauon/issues/1088 , however, XSPF tags like `<title>`, `<creator>`, and `<album>` should not be encoded by `urllib.parse.quote`. Only content of the _`<location>`_ tag should be encoded that way to comply with the Spec.

**Comment by C0rn3j** [comment]
https://www.xspf.org/spec#62-relative-paths

That does check out since the spec mentions this has to be done for paths and none of those tags should have a path.

Wanna send a PR for this?

**Comment by iamalexei** [comment]
> Wanna send a PR for this?

Yes, sure. I have an idea how to rewrite that part, which creates xspf playlists, using xml.etree.ElementTree (as it's already used in t_main.py). xml.etree.ElementTree escapes just `<`, `>`, and `&` symbols in a tag's content out of the box to produce a valid XML.

**Comment by C0rn3j** [comment]
I would imagine reverting the commit you linked partially for the three lines it shouldn't be in would do the trick?

**Comment by iamalexei** [comment]
You're right, it would. On the other hand, my rationale is that using xml.etree.ElementTree to create an xspf will make that part of the code less prone to typos in the future. Compare: `xport.write('      <location>' + urllib.parse.quote(path) + '</location>\n')` with 
```python
location_tag = ET.SubElement(track_tag, "location")
location_tag.text = urllib.parse.quote(path)
```
For example, accidentally deleting or adding one space will mess formatting of the output file in the first case. Also, you have to keep in mind indentation level of a parent tag.

@C0rn3j in your oppinion, is "track_tag", "location_tag", etc. a good way to name vars in this case?

**Comment by C0rn3j** [comment]
XML doesn't care about indents - https://stackoverflow.com/questions/12526438/importance-of-indenting-xml-file

> in your opinion, is "track_tag", "location_tag", etc. a good way to name vars in this case?

It's fine, though `xml_track_tag` (etc) might be even better.

**Comment by iamalexei** [comment]
> XML doesn't care about indents - https://stackoverflow.com/questions/12526438/importance-of-indenting-xml-file

I know, it's just me worrying about small details and maintainability of the code.



> It's fine, though `xml_track_tag` (etc) might be even better.

Is `xml_track_tag` or `xspf_track_tag` better?

**Comment by C0rn3j** [comment]
> Is xml_track_tag or xspf_track_tag better?

Either is fine to me

> I know, it's just me worrying about small details and maintainability of the code.

I mean if you want to convert it to use a proper XML library, I don't see why not, I am personally not familiar with and was just suggesting the fastest way forward :)

**Comment by iamalexei** [comment]
Right now I'm also trying to add a new `trackNum` tag to xspf export, so in this case I hope this will be faster for me: 
```python
xspf_tracknum_tag = ET.SubElement(xspf_track_tag, "trackNum")
xspf_tracknum_tag.text = track.track_number
```
than counting spaces and manually creating opening and closing tag strings.

> I am personally not familiar with and was just suggesting the fastest way forward :)

Thank you! Your suggestion is really the fastest way when only change in encoding tags needed.
