### ISSUE TITLE
Guitarparty.com is dead

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/Tauon#1342]
https://guitarparty.com looks like someone bought it and api subdomain does not even resolve anymore.

**Comment by Taiko2k** [comment]
We could probably just remove this feature to lighten the maintenance burden. Unless users ask for it back... I'm not sure if *any* users are currently using it.

**Comment by C0rn3j** [comment]
Actually, now that I am looking at it closer, the website still seems alive, just a bit confusing. 

https://www.guitarparty.com/songs/fireflies/

The *old* API is dead, but there is a new(?) one.

https://www.guitarparty.com/api/v3/core/

https://www.guitarparty.com/api/v3/core/songbooks/
