### ISSUE TITLE
Issue with Spotify authorization

### ISSUE THREAD

**Issue by Fooughhy** [Taiko2k/Tauon#1349]
Using Tauon version 7.8.0, running Windows 10.

I have setup Spotify in Tauon using my Client ID and the Client Secret. I have an application in the Spotify Dashboard with the status "Development mode". When I press "Authorise" in the Tauon app it opens a webpage on "http://localhost:7811/spotredir?code=" and it says "You can close this now and return to Tauon Music Box". I also have the "Enable" option toggled:
![image](https://github.com/user-attachments/assets/f48bd57e-0aa6-4f37-84d1-8aeb4096ba8a)

I would assume this means that Tauon is setup to function with Spotify correctly.

But when I open the hamburger-menu in the "playback bar" at the bottom of the application, select "Import Spotify" and select any option there, I see a popup with "Please authorise and click the enable toggle first".

Why is this not working?

**Comment by Taiko2k** [comment]
Sounds like you're doing it right. It might just be broken in that version unfortunately.

**Comment by C0rn3j** [comment]
@Fooughhy can you reproduce this issue on 7.9.0?

I have fixed Windows builds in https://github.com/C0rn3j/Tauon/tree/buildfixes, if you're feeling up for it, you can try following that repo together with https://github.com/Taiko2k/Tauon/wiki/Building-for-Windows
