### ISSUE TITLE
Change for building on linux

### ISSUE THREAD

**Issue by brunob** [Taiko2k/Tauon#1351]
Hi, i've seen that the main script has been change on https://github.com/Taiko2k/Tauon/wiki/Building ref https://github.com/Taiko2k/Tauon/wiki/Building/_compare/18edb1de1c26ee286684a5c7178f8aa71931a3c1...038cb7f2c040bc47e8bc3e26a4018ed634ccc601

If i try to launch `python __main__.py` from the top folder it can't work, for sure `__main__.py` is not there, so if i try with `python src/tauon/__main__.py` it works but it create new `cache` & `user-data` folders in `src/tauon`.

Do i simply have to move my existing `cache` & `user-data` folders to `src/tauon` or is there a smarter way to handle this ?

**Comment by C0rn3j** [comment]
> `__main__.py is not there, so if i try with python src/tauon/__main__.py`

Good catch, fixed.

> Do i simply have to move my existing cache & user-data folders to src/tauon or is there a smarter way to handle this ?

Hmm, it's unfortunate that moving things around now requires people to move the dir, that should probably be handled automatically before the next release.

Relevant code for handling this in the current state is here - 

https://github.com/Taiko2k/Tauon/blob/2d409c783a9e96bf681e7daf8aa1658375d9b9fa/src/tauon/t_modules/t_main.py#L560-L637

> is there a smarter way to handle this

There are other ways but I am not sure about them being smarter, simply moving the directories seems the way to go for now.

**Comment by brunob** [comment]
Thx for the feedback, moving data dirs is the fix i applied, feel free to close the issue :)

**Comment by C0rn3j** [comment]
I've added a mention to the changelog at least, so it's not completely forgotten.

**Comment by C0rn3j** [comment]
Note that this will get reverted by the current state of #1361 and it will be back in the project root.
