### ISSUE TITLE
^C signal is not caught, requiring to focus UI to process kill

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/Tauon#1357]
A bit annoying when developing and wanting to kill Tauon purely from the terminal.

**Comment by Taiko2k** [comment]
OK fix committed

**Comment by C0rn3j** [comment]
Testing the https://github.com/Taiko2k/Tauon/actions/runs/12474705061 build, I can still do it.

![image](https://github.com/user-attachments/assets/de7c0cc0-6939-4562-aa1e-ea7e8fcfd54c)

It does eventually pick up on it but it takes about 20 seconds

**Comment by Taiko2k** [comment]
Strangely the signal doesn't cause an interrupt with SDL. Ive now committed a workaround that lowers the currently set event timeout from 20s to 1s.
