### ISSUE TITLE
Tauon does not fully load when it is started in the background.

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/Tauon#229]
Hi, I used bspwm rules to start tauon on boot on another desktop. When I tried to start playing music with my media keys without going to that desktop, it did not work. When I went to it, I saw Tauon startup splash screen, then it finally loaded. I was then able to control it using the media keys. 
The rule I used to send it to a deskotp is `bspc rule -a "Tauon Music Box" desktop='^9'`
I use `python3 /opt/tauon-music-box/tauon.py %U &` in my autostart script to start it on boot. 

Here is what was shown in the command line when I started from terminal:

```
python3 /opt/tauon-music-box/tauon.py %U                
Tauon Music Box v5.1.4
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/ted/.local/share/TauonMusicBox
Found XDG-Downloads: /home/ted/Downloads
Found XDG-Music: /home/ted/Music
Install directory: /opt/tauon-music-box
Dev mode, ignoring single instancing
```
It stopped here for as long as I was still focusing on the terminal desktop. When I switched to desktop 9 where tauon is loaded, It proceeded to show this:

```
Database loaded in 0.044 seconds.
Locale detected: en_US
No translation file available
Could not connect to gnome media keys
Using SDL version: 2.0.10
Config reload theme...
Applying external theme: Vape
Theme number: 10
Enabling garbage collecting
```
Taoun version: 5.1.4-2
bspwm version: bspwm-manjaro 0.9.7-5
kernel: 5.4.8-2-MANJARO
python verison: 3.8.1-1

**Comment by Taiko2k** [comment]
This seems like it will be a little difficult for me to debug. I'm almost certain it will be related to an external library. Probably stalls with SDL when it creates the window.

If you're interested in narrowing it down, try edit `tauon.py` and search for `t_window = SDL_CreateWindow(`. Try place a print statement e.g. `print("test1")` before and after that call and see if it reaches it. You could also try it around the line `SDL_Init(SDL_INIT_VIDEO)`.

If it is SDL related then its kinda out of scope for *me* to fix unfortunately.

**Comment by keystroke3** [comment]
It i put `calling sdl` and `sdl called` before and after the `SDL` part respectively. I also did the same with `t_window`.  `sdl called` was executed, but `t_window called` was not:

```
Tauon Music Box v5.1.4
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Running from installed location
User files location: /home/ted/.local/share/TauonMusicBox
Found XDG-Downloads: /home/ted/Downloads
Found XDG-Music: /home/ted/Music
Install directory: /opt/tauon-music-box
Dev mode, ignoring single instancing
calling sdl
sdl called
calling t_window
```

**Comment by Taiko2k** [comment]
So it must be related to SDL creating the window.

A workaround could be to load the audio related subsystems first... but unfortunately that would be a lot of work to untangle for such an edge case. I might have to go with wontfix for this. :sweat:

**Comment by keystroke3** [comment]
It's OK. I will have to deal with it in other ways. Maybe I might go through the code and see if I can come up with a fix.

**Comment by C0rn3j** [comment]
Closing since there's been 5 years of updates since the last comment, open a new issue if this still happens.

There are now CI prebuilts of Tauon you can use for testing too with #1354.
