### ISSUE TITLE
[Bug] Registering keystrokes from external GUI

### ISSUE THREAD

**Issue by demeralde** [Taiko2k/Tauon#392]
I'm using i3. I can type `Super` + `Space` to search for an app and launch it. When I hit `Enter` in this, it registers the keystroke in Tauon. I've also noticed the same thing with a few other things.

Other apps don't seem to do this, so I don't think it's an issue related to my WM.

**Comment by awsms** [comment]
The same thing happens to me quite frequently while pressing Alt+TAB on Cinnamon. It's not systematic like you though.

**Comment by Taiko2k** [comment]
@dspacejs When focusing or leaving the window? For leaving, I can just ignore those key presses if <kbd>Super</kbd> is held down.

**Comment by dspacejs** [comment]
@Taiko2k not sure if the window counts as focused or not. I assumed opening up a modal like this would automatically blur the focus. The `Super` key thing might work for some things, although it won't for others like what @awsms said

**Comment by Taiko2k** [comment]
Tell me if you're still getting this with v6.3.3

**Comment by dspacejs** [comment]
@Taiko2k seems to be fixed. Will open again if I notice problems

**Comment by dspacejs** [comment]
@Taiko2k looks like this issue is still present. Let me know if I can provide any more info for debugging

**Comment by Taiko2k** [comment]
Basically, if keyboard presses are being sent to the window when they shouldn't, isn't that the WM's job? I can only try work around issues by ignoring certain key combinations. So my question really is, what pattern should Tauon ignore?

**Comment by dspacejs** [comment]
@Taiko2k not sure, it might be the WM's problem. I haven't tested this in a different GUI. Does it happen on any other WM?

**Comment by ritlew** [comment]
I have this issue on kde plasma when I use rofi

**Comment by Taiko2k** [comment]
@ritlew Which button is Tauon registering? Also, can you confirm this issue on latest git master.

Does this happen on exiting exiting Tauon window focus, entering window focus, or both?

**Comment by ritlew** [comment]
Here's an example:

- I'm playing a song in tauon
- I select a different song (but don't play)
- I open rofi with super+D
- I type "firefox" and hit enter
- The enter registers in tauon as the focus returns to tauon and plays the song I selected

I'll check master and let you know

**Comment by ritlew** [comment]
It occurs on master

**Comment by Taiko2k** [comment]
Okay, I believe this may be fixed now. Try pull and test again.

**Comment by ritlew** [comment]
Seems to be fixed
