### ISSUE TITLE
[Bug] Folder files not included when adding folder if the added folder contains subfolders

### ISSUE THREAD

**Issue by GLLM** [Taiko2k/Tauon#431]
Hello,

first : I've just discovered this nice player and woohooo I might have found what I've been looking for since I left windows (and its a-ma-zing AIMP4) for Linux !!

The library management per folders still is a mystery to me, as to how to add folders located in different disks or how to sort the folders differently from the playlist ...

Anyway, for clarity : here how one of my 2 folders is organized

TOP_FOLDER (no files)
  L Subfolder A (have files)
    L Sub_Subfolder A1 (have files)
    L Sub_Subfolder A2 (have files)
    L Sub_Subfolder A3 (have files)
  L Subfolder B (have files)  
    L Sub_Subfolder B1 (have files)
    L Sub_Subfolder B2 (have files)
    L Sub_Subfolder B3 (have files)

When adding the top folder (TOP_FOLDER), files contained in Subfolder A & Subfolder B are not added to the library (or not visible) ...

I suspect as soon as a folder has subfolders, its own files are not added/visible.

It's happening with dozens of folders here.
I've removed and re-added them, to no avail.

Thanks,
GLLM

**Comment by Taiko2k** [comment]
This should work as expected. Try double check the tracks you're looking for aren't in the playlist somewhere. Note that folders are ordered before files, so in your example, A1, A2's, and A3's tracks will appear *before* A's tracks.
