### ISSUE TITLE
Using Notification Area with XFCE causes a segmentation fault when clicking on the tray icon

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/Tauon#445]
![image](https://user-images.githubusercontent.com/19501722/104091631-db16e600-527e-11eb-8e49-a10c43d252d3.png)

When I use this tray instead of the Status Notifier Plugin, clicking on the Tauon icon causes a segmentation fault:

```
[1]    22532 segmentation fault (core dumped)  ./tauon.py
```

(The issue from #441 also applies to this tray, before playing a song clicking on it does nothing.)

**Comment by Sonico98** [comment]
This started happening to me about two days ago too, but I'm using i3wm with polybar's tray.
`/usr/bin/tauon: line 13: 146552 Segmentation fault      (core dumped) python3 /opt/tauon-music-box/tauon.py "$@"`
Right now I'm using the version on the AUR, but I tried with the flatpak and got the same result.

**Comment by C0rn3j** [comment]
Is this still the case on the current version?

**Comment by C0rn3j** [comment]
Closing since no response and it has last been a problem 3 years ago, open a new issue with new logs if it still happens on current master.
