### ISSUE TITLE
Locks up importing files

### ISSUE THREAD

**Issue by mabushey** [Taiko2k/Tauon#492]
My files are located on a ZFS server, shared via NFS 4. Tauon was install on Arch via `yay -Suy tauon-music-box`. I did a drag n drop of the music folder to Tauon. It started to import. I left the room to 20 minutes, and after I came back it displayed `Scanning Tags... 22274 remaining` in the titlebar, and has been there for a full day. I just held down the page down key to try to scroll down (there is no scroll bar) and after about 40 seconds of fast scrolling the program appears to have crashed - it just vanished. I restarted Tauon, the titlebar showed `Scanning Tags...`, and immediately started decrementing. After a minute or so it stopped decrementing once again at  `Scanning Tags... 22274 remaining`. Is there a log file where I can see what's giving it a problem?

**Comment by Taiko2k** [comment]
Launch the app from terminal using the command `tauon`, when it crashes or the import stalls, hopefully there will be a detailed error printed.

**Comment by C0rn3j** [comment]
Closing since OP never got back with details.
