### ISSUE TITLE
Visualization in the Showcase view has low fps

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/Tauon#526]
On my PC with Nvidia GPU Visualization in the Showcase view has a very low fps. Works fine on another PC.
Solus Budgie, Tauon flatpak.

PS: thanks for bringing back visualization!

**Comment by C0rn3j** [comment]
Still the case in latest prebuilt images from #1354 and up to date GPU drivers?

Or even the 7.8.3 flatpak, since this is quite dated?

**Comment by Solarunit** [comment]
I will check later

**Comment by C0rn3j** [comment]
I now think it's the same issue as here https://github.com/Taiko2k/Tauon/issues/979#issuecomment-2559937670 and rendering the albumart is extremely costly for some reason.

**Comment by Solarunit** [comment]
Visualization works fine. Closing issue.
