### ISSUE TITLE
[Bug] Internet Radio do not resume after waking up from sleep/hibernation (Kubuntu 21.04)

### ISSUE THREAD

**Issue by GLLM** [Taiko2k/Tauon#538]
Hello !

I'm using Kubuntu 21.04 with Tauon MB 6.6.0 (flatpak)

After the system wakes up from sleep/hibernation, and because the network halted during sleep, the Internet Radio play does not resume playing.
When a normal playlist (local files) was suspended because of sleep/hibernation, when the system wakes up, the playback resumes normally.

I think it should work the same with internet radios.

Thanks
GLLM

**Comment by Taiko2k** [comment]
It's actually intended that audio stops on sleep, so it not doing that is more the bug. (Though it is likely the loss of connection causing radio to stop in this case)

**Comment by GLLM** [comment]
Hi @Taiko2k, 
so it's intended the play does not restart after waking up from sleep ?
Why this difference between local files and webstreams, if I may ?

Thanks
GLLM

**Comment by Taiko2k** [comment]
> so it's intended the play does not restart after waking up from sleep

Yeah, it was the idea

>  Why this difference between local files and webstreams, if I may ?

It seems to be not detecting that there was a system suspend. But webstreams will always stop when the connection gets interrupted anyway.

**Comment by GLLM** [comment]
> It seems to be not detecting that there was a system suspend. But webstreams will always stop when the connection gets interrupted anyway.

Oh !! no retry at all ?
It would be lovely to have this tho, like with a setting : retry x times if stream fails.
A simple wifi issue, or foot in the RJ45 cable and voilà .... no music anymore ! :-/
I think a lot of music player have a webstream retry mecanism.

Thanks
GLLM

**Comment by GLLM** [comment]
Still hoping for this one ... Which bothers me on a daily basis (true).
I'll try setting a bigger cache for network radio, if I can.

#FingersCrossed

**Comment by Taiko2k** [comment]
Okay, I've now committed a new option called *Resume from suspend* under Settings > Function > Page 4. This is set to off by default.

Once you upgrade, let me know if that's working for you.

Btw yeah, that cache setting has no effect on the radio. Note that Tauon does not support pausing while continuing to buffer the stream. Its either playing (near) live or stopped.

**Comment by GLLM** [comment]
@Taiko2k many thanks. Will test as soon as I get a version with the fix :+1:

**Comment by C0rn3j** [comment]
@GLLM did it end up fixing the issue for you?

**Comment by GLLM** [comment]
I wouldn't know. As I've not used Tauon for a long time. Sorry :-/

**Comment by C0rn3j** [comment]
Closing then, thanks for getting back
