### ISSUE TITLE
Exception during syncing when writing a file with a character FAT32 doesn't support

### ISSUE THREAD

**Issue by line72** [Taiko2k/Tauon#576]
My MP3 player's Hard drive is FAT32 (vfat). This file system has limited support for special characters. When I am trying to sync my playlist to my music player, if the original file has one of these characters (e.g. '?') in the filename, then it fails to sync, and raises the following exception:

```python
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_main.py", line 16909, in auto_sync_thread
    shutil.copyfile(os.path.join(encode_done, file), os.path.join(os.path.join(path, item), file))
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: '/run/media/dillavou/X1/The Flaming Lips - The Soft Bulletin/06 - What Is The Light?.mp3'
```

The sync process needs to have knowledge of the destination file type and make sure to automatically strip or replace any characters that the filesystem cannot handle.

**Comment by C0rn3j** [comment]
![image](https://github.com/user-attachments/assets/70c5aba3-24de-460c-9cf2-9d87f1be03f0)

Thanks for the detailed report!

This will be fixed in 7.9.0.
