### ISSUE TITLE
No sound when switching from the radio to the playlist

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/Tauon#675]
No sound when switching from the playing song on the radio to the local playlist. Only player restart helps.
v7.1.0 Flatpak version (and older version had this issue too iirc)

**Comment by Taiko2k** [comment]
I've received this report from other people as well, but I've been unable to replicate the issue.

**Comment by Solarunit** [comment]
So I made a test: 

1. Radio was playing ~1 minute
2. Double click to start playing local song from the playlist
3. Approx. 2 seconds after that, radio continues to play
4. Silence, also not possible to play another song in the playlist

**Comment by Taiko2k** [comment]
Yeah I get the method, just weirdly it works normally for me. So hard to track this bug down

**Comment by Solarunit** [comment]
"Works for me" on Listen.more | Jpop. :man_shrugging:

**Comment by Taiko2k** [comment]
Can you retest this with v7.1.2? Does the issue persist?

**Comment by Solarunit** [comment]
v7.1.2 still have this problem

**Comment by C0rn3j** [comment]
Could you retest again on current git master and post the log here if it still happens?

**Comment by Solarunit** [comment]
v7.8.3 flatpak, can't reproduce. Closing it for now.
