### ISSUE TITLE
Crash on startup: X Error

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/Tauon#768]
Hey there. Just recently got this issue. Tauon does not start. Here is the output from the command line:

```
No previous window state
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  159
  Current serial number in output stream:  160
```

I also have `python-httpx` installed.

Im on arch linux. Running latest our version of the Tauon. Anything i can do to fix this?

_Originally posted by @talhakerpicci in https://github.com/Taiko2k/TauonMusicBox/issues/750#issuecomment-1148860910_

**Comment by C0rn3j** [comment]
I think we can close this since nobody has complained about X crashes since then from what I can see - outside of Flatpak builds, which are its own issue - and it has been 2.5 years.

**Comment by FelixDz** [comment]
Just for information, I'm getting a very similar error with the latest version (8.2.2), and this is the first time I try Tauon so a made no config changes whatsoever:
```
2025-11-12 23:53:55 [ INFO  ] [ __main__ ] No window state file
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  417
  Current serial number in output stream:  418
```

I installed the AUR version on Archlinux, I'll give the Flatpak version a try.

EDIT: the Flatpak version works like a charm. Maybe this is a dependency problem?
