### ISSUE TITLE
High cpu usage by ffmpeg

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/Tauon#824]
When playing a radio in Tauon, i noticed a high cpu usage by ffmpeg process (PPID is Tauon)

![](https://i.imgur.com/e3xW2py.png)

I assume ffmpeg is only used when radio playing. Can we improve the cpu usage?

**Comment by Taiko2k** [comment]
That's not normal, its <0.1% for me. Does it do that for you with other stations selected?

**Comment by Solarunit** [comment]
The high cpu usage with listen.more-jpop radio. I will test with others.

**Comment by C0rn3j** [comment]
@Solarunit is this still an issue today?

**Comment by Solarunit** [comment]
@C0rn3j  haven't noticed it lately. I will close it.
