### ISSUE TITLE
Tauon only shows a black window upon launch

### ISSUE THREAD

**Issue by denppa** [Taiko2k/Tauon#899]
Fedora 37 Silverblue, Gnome 43.2, Wayland, i7 6th gen, 980ti.

Installed tauon music box through flatpak, but only displays a black blank window upon launch.

Output when ran from terminal:
```
$ flatpak run com.github.taiko2k.tauonmb 
Tauon Music Box v7.4.6
Copyright 2015-2022 Taiko2k captain.gxj@gmail.com

Window size: [1120, 600]
Detected running as Flatpak
Installed as Flatpak
User files location: /var/home/user.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /var/home/user/Downloads
Found XDG-Music: /var/home/user/Music
Install directory: /app/bin
Database loaded in 0.0 seconds.
Copy tray icons to data directory...
Scanning for chromecasts...
Start controller server
Start PHAzOR backend...
Using SDL version: 2.0.16
Applying theme: Turbo
```

**Comment by Taiko2k** [comment]
Happens often with NVIDIA and flatpak, running `flatpak update` usually fixes it.

**Comment by Horuyuki** [comment]
What flatpak spat out:
```
$ flatpak update
Looking for updates…

Info: (pinned) runtime org.fedoraproject.Platform branch f35 is end-of-life, with reason:
   Fedora 35 runtime is no longer supported.

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.


        ID                                  Branch Op Remote  Download
 1. [✓] org.freedesktop.Platform.GL.default 20.08  i  flathub 106.9 MB / 106.4 MB

Installation complete.
```
But still black upon launch.

**Comment by Taiko2k** [comment]
Hmm, I can only think to try do a system update and reboot, then run that command again.

**Comment by Horuyuki** [comment]
Just did that. Tried to disable gpu by adding the option `--disable-gpu` to flatpak command. Both did not help.

**Comment by Taiko2k** [comment]
Could be that a new NVIDIA driver was released but flatpak hasn't gotten an update for it, might need to wait and see.

**Comment by Solarunit** [comment]
> Could be that a new NVIDIA driver was released but flatpak hasn't gotten an update for it, might need to wait and see.

this happened for me once

**Comment by C0rn3j** [comment]
Closing as there hasn't been anyone reporting this issue for 2 years.

If this is still an issue, try with the hopefully-soon-upcoming 7.9.0 and post the log again.
