### ISSUE TITLE
[Feature Request] Button to refresh Spotify "session"

### ISSUE THREAD

**Issue by JYSN** [Taiko2k/Tauon#995]
So first, absolute thanks for all the work with Tauon, was super stoked when it became available on Windows after a few years loyally using on linux.

Sort of a hotfix, but since the recommended solution to issues playing music through the Spotify integration is close and reopen Tauon, is there any way we could get a button in the menu bar to refresh the session, or reboot the component responsible for the current connection to spotify, without closing tauon as a whole? 
I've noticed issues (Win10, latest release) with reopening Tauon too soon after closing and it either not reopening or not solving the issue, so usually wait a while to reopen and end up forgetting. Before streaming through TauonMB was available, used to use the "Start Spotify remote" and "Stop Spotify Remote" to similar ends with that feature. Feel like having some indicator within Tauon like "refreshing session" while it reloads the component would be a nice quality of life update, especially since the session usually gets borked anytime Tauon's left open while the computer is suspended ( especially if Spotify is used on another device during that time).

Thanks

**Comment by Taiko2k** [comment]
Ideally we wouldn't need a manual restart button, Tauon should work it out automatically. There are improvements that are needed here. Ill do some experimenting and get back to you.

**Comment by Taiko2k** [comment]
OK Ive committed some fixes for some bugs I found. Ive made a new release now too. It should stop working less now I think.

**Comment by C0rn3j** [comment]
I've tagged this as to be fixed by the PR that fixes up Windows support, if you still have an issue on 7.9.0, open a new issue please.
